# Generated by Django 3.1.3 on 2020-12-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0004_ascentstyle_light_orientation_rocktype_routecharacter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "nick_name",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("ascent_time_min", models.IntegerField(default=0)),
                ("max_height_in_m", models.IntegerField(default=0)),
                ("rain_protected", models.BooleanField(default=False)),
                ("child_friendly", models.BooleanField(default=False)),
                ("windy", models.BooleanField(default=False)),
                ("ascent_description", models.CharField(blank=True, max_length=1000)),
                ("descent_description", models.CharField(blank=True, max_length=1000)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
                ("altitude", models.FloatField(default=0)),
                (
                    "fk_light",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lights",
                        to="ocdb.light",
                    ),
                ),
                (
                    "fk_orientation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientations",
                        to="ocdb.orientation",
                    ),
                ),
                (
                    "fk_sector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="ocdb.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiaryPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diaries",
                        to="ocdb.diary",
                    ),
                ),
                (
                    "fk_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to="ocdb.person",
                    ),
                ),
            ],
        ),
    ]
