# Generated by Django 3.1.3 on 2020-12-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0005_diary_diaryperson_person_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("length_in_m", models.IntegerField(default=0)),
                ("protection", models.CharField(blank=True, max_length=1000)),
                ("equipment", models.CharField(blank=True, max_length=1000)),
                ("hints", models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="RouteGrades",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_ascent_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_characters",
                        to="ocdb.ascentstyle",
                    ),
                ),
                (
                    "fk_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="ocdb.grade",
                    ),
                ),
                (
                    "fk_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_routes",
                        to="ocdb.route",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("fk_ascent_style", "fk_grade"),
                    ("fk_route", "fk_ascent_style"),
                },
            },
        ),
        migrations.CreateModel(
            name="RouteCharacters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="ocdb.route",
                    ),
                ),
                (
                    "fk_route_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_characters",
                        to="ocdb.routecharacter",
                    ),
                ),
            ],
            options={
                "unique_together": {("fk_route", "fk_route_character")},
            },
        ),
    ]
