# Generated by Django 3.1.3 on 2020-12-04 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0005_diary_diaryperson_person_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("length_in_m", models.IntegerField(default=0)),
                ("protection", models.CharField(blank=True, max_length=1000)),
                ("equipment", models.CharField(blank=True, max_length=1000)),
                ("hints", models.CharField(blank=True, max_length=1000)),
                (
                    "fk_rock_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_rock_types",
                        to="ocdb.rocktype",
                    ),
                ),
                (
                    "fk_sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_sectors",
                        to="ocdb.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ascent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=1000)),
                (
                    "ascent_number",
                    models.IntegerField(
                        blank=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "fk_ascent_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ascent_styles",
                        to="ocdb.ascentstyle",
                    ),
                ),
                (
                    "fk_diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ascent_diaries",
                        to="ocdb.diary",
                    ),
                ),
                (
                    "fk_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ascent_routes",
                        to="ocdb.route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteGrades",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_ascent_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_characters",
                        to="ocdb.ascentstyle",
                    ),
                ),
                (
                    "fk_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="ocdb.grade",
                    ),
                ),
                (
                    "fk_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_routes",
                        to="ocdb.route",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("fk_route", "fk_ascent_style"),
                    ("fk_ascent_style", "fk_grade"),
                },
            },
        ),
        migrations.CreateModel(
            name="RouteCharacters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="ocdb.route",
                    ),
                ),
                (
                    "fk_route_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_characters",
                        to="ocdb.routecharacter",
                    ),
                ),
            ],
            options={
                "unique_together": {("fk_route", "fk_route_character")},
            },
        ),
        migrations.CreateModel(
            name="RopeParty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_ascent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rope_party_ascents",
                        to="ocdb.ascent",
                    ),
                ),
                (
                    "fk_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rope_party_persons",
                        to="ocdb.person",
                    ),
                ),
            ],
            options={
                "unique_together": {("fk_ascent", "fk_person")},
            },
        ),
        migrations.CreateModel(
            name="FirstAscentionistRoute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_ascentionist_person",
                        to="ocdb.person",
                    ),
                ),
                (
                    "fk_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_ascentionist_routes",
                        to="ocdb.route",
                    ),
                ),
            ],
            options={
                "unique_together": {("fk_route", "fk_person")},
            },
        ),
    ]
