# Generated by Django 3.1.4 on 2020-12-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ocdb",
            "0006_ascent_firstascentionistroute_ropeparty_route_routecharacters_routegrades",  # noqa: E501
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
