# Generated by Django 3.1.4 on 2021-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0010_auto_20210203_2304"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sector",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="sector",
            constraint=models.UniqueConstraint(
                fields=("name", "fk_sector"), name="unique_with_fk_sector"
            ),
        ),
        migrations.AddConstraint(
            model_name="sector",
            constraint=models.UniqueConstraint(
                condition=models.Q(fk_sector=None),
                fields=("name",),
                name="unique_without_fk_sector",
            ),
        ),
    ]
