# Generated by Django 3.1.4 on 2021-03-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0012_sector_name_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="source",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="sector",
            name="sub_id_in_parent_sector",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
