# Generated by Django 3.1.4 on 2021-03-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0013_auto_20210303_2125"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="name_alt",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
