# Generated by Django 3.1.4 on 2021-03-04 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0015_auto_20210303_2236"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstascentionistroute",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="route",
            name="first_ascent_date",
            field=models.DateField(blank=True, default=datetime.date(9999, 9, 9)),
        ),
    ]
