# Generated by Django 3.1.4 on 2021-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0017_auto_20210304_2118"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sector",
            old_name="ascent_description",
            new_name="approach",
        ),
        migrations.RenameField(
            model_name="sector",
            old_name="descent_description",
            new_name="descent",
        ),
        migrations.AddField(
            model_name="sector",
            name="approach_road",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="sector",
            name="internal_rating",
            field=models.IntegerField(default=0),
        ),
    ]
