# Generated by Django 3.1.4 on 2021-03-08 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0018_auto_20210305_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="fk_orientation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_orientations",
                to="ocdb.orientation",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="internal_rating",
            field=models.IntegerField(default=0),
        ),
    ]
