# Generated by Django 3.1.4 on 2021-03-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0019_auto_20210308_1954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="length_in_m",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="sector",
            name="max_height_in_m",
            field=models.FloatField(default=0),
        ),
    ]
