# Generated by Django 3.2.9 on 2021-12-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0020_auto_20210308_2143"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sector",
            name="unique_without_fk_sector",
        ),
    ]
