# Generated by Django 3.2.9 on 2021-12-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocdb", "0021_remove_sector_unique_without_fk_sector"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="routegrades",
            unique_together={("fk_route", "fk_ascent_style", "fk_grade")},
        ),
        migrations.AddConstraint(
            model_name="sector",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fk_sector", None)),
                fields=("name",),
                name="unique_without_fk_sector",
            ),
        ),
    ]
